docker pull docker.1ms.run/bitnami/redis:latest &
docker pull docker.1ms.run/prom/prometheus:v2.27.1 &
docker pull docker.1ms.run/busybox:1.36.0 &
docker pull docker.1ms.run/mpioperator/kubectl-delivery:latest &
docker pull docker.1ms.run/docker:23.0.4 &
docker pull docker.1ms.run/projecthami/hami:v2.3.13 &
docker pull docker.1ms.run/nvidia/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 &
docker pull docker.1ms.run/prom/node-exporter:v1.5.0 &
docker pull docker.1ms.run/kubeflow/training-operator:v1-8a066f9 &
docker pull docker.1ms.run/nvidia/k8s-device-plugin:v0.11.0-ubuntu20.04 &
docker pull docker.1ms.run/ubuntu:20.04 &
docker pull docker.1ms.run/volcanosh/vc-scheduler:v1.7.0 &
docker pull docker.1ms.run/kubernetesui/metrics-scraper:v1.0.8 &
docker pull docker.1ms.run/istio/pilot:1.15.0 &
docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.25.16 &
docker pull docker.1ms.run/alpine:3.10 &
docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0 &
docker pull docker.1ms.run/carlosedp/addon-resizer:v1.8.4 &
docker pull ccr.ccs.tencentyun.com/cube-argoproj/argoexec:v3.4.3 &
docker pull docker.1ms.run/mysql:8.0.32 &
docker pull docker.1ms.run/grafana/grafana:9.5.20 &
docker pull ccr.ccs.tencentyun.com/cube-argoproj/argocli:v3.4.3 &
docker pull docker.1ms.run/postgres:11.5 &
docker pull docker.1ms.run/volcanosh/vc-webhook-manager:v1.7.0 &
docker pull quay.io/prometheus-operator/prometheus-operator:v0.46.0 &
docker pull docker.1ms.run/liangjw/kube-webhook-certgen:v1.1.1 &
docker pull docker.1ms.run/kubebuilder/kube-rbac-proxy:v0.14.1 &
docker pull docker.1ms.run/kubernetesui/dashboard:v2.6.1 &
docker pull docker.1ms.run/python:3.9 &
docker pull docker.1ms.run/istio/proxyv2:1.15.0 &
docker pull docker.1ms.run/minio/minio:RELEASE.2023-04-20T17-56-55Z &
docker pull ccr.ccs.tencentyun.com/cube-argoproj/workflow-controller:v3.4.3 &
docker pull docker.1ms.run/volcanosh/vc-controller-manager:v1.7.0 &
wait
